'use strict';

angular.module('app')
    .constant("globalConstants",
    {
        gradeOptions: [
            { text: '12' },
            { text: '11' },
            { text: '10' },
            { text: '9' },
            { text: '8' },
            { text: '7' },
            { text: '6' },
            { text: '5' },
            { text: '4' },
            { text: '3' },
            { text: '2' },
            { text: '1' },
            { text: 'KINDERGARTEN'},
            { text: 'PREKINDERGARTEN' },
            { text: 'STAFF' },
            { text: 'OTHER' },
            { text: 'COMBOCLASS'}

        ],

        maybe: 2,
        yes: 1,
        no: 0,
        annually: 'annually',
        monthly: 'monthly',
        biweekly: 'biweekly',
        permanent: 0,
        temporary: 1,
        dateFormat: 'MM-dd-yyyy',
        create: 0,
        modify: 1,
        lifelineImageType: 0,
        superadministratorRoleName: "Super Administrator",
        superadministratorRoleRank: 0,
        administratorRoleName: "Administrator",
        administratorRoleRank: 1,
        states: [
            { id: 0, text: 'AL' },
            { id: 1, text: 'AK' },
            { id: 2, text: 'AZ' },
            { id: 3, text: 'AR' },
            { id: 4, text: 'CA' },
            { id: 5, text: 'CO' },
            { id: 6, text: 'CT' },
            { id: 7, text: 'DE' },
            { id: 8, text: 'FL' },
            { id: 9, text: 'GA' },
            { id: 10, text: 'HI' },
            { id: 11, text: 'ID' },
            { id: 12, text: 'IL' },
            { id: 13, text: 'IN' },
            { id: 14, text: 'IA' },
            { id: 15, text: 'KS' },
            { id: 16, text: 'KY' },
            { id: 17, text: 'LA' },
            { id: 18, text: 'ME' },
            { id: 19, text: 'MD' },
            { id: 20, text: 'MA' },
            { id: 21, text: 'MI' },
            { id: 22, text: 'MN' },
            { id: 23, text: 'MS' },
            { id: 24, text: 'MO' },
            { id: 25, text: 'MT' },
            { id: 26, text: 'NE' },
            { id: 27, text: 'NV' },
            { id: 28, text: 'NH' },
            { id: 29, text: 'NJ' },
            { id: 30, text: 'NM' },
            { id: 31, text: 'NY' },
            { id: 32, text: 'NC' },
            { id: 33, text: 'ND' },
            { id: 34, text: 'OH' },
            { id: 35, text: 'OK' },
            { id: 36, text: 'OR' },
            { id: 37, text: 'PA' },
            { id: 38, text: 'RI' },
            { id: 39, text: 'SC' },
            { id: 40, text: 'SD' },
            { id: 41, text: 'TN' },
            { id: 42, text: 'TX' },
            { id: 43, text: 'UT' },
            { id: 44, text: 'VT' },
            { id: 45, text: 'VA' },
            { id: 46, text: 'WA' },
            { id: 47, text: 'WV' },
            { id: 48, text: 'WI' },
            { id: 49, text: 'WY' },
            { id: 50, text: 'PR' }
        ],
        accordions: {
            eligibility: 'application-eligibility',
            applicant: 'application-applicant',
            addresses: 'application-addresses',
            hoh: 'application-hoh',
            agreements: 'application-agreements',
            qualification: 'application-qualification',
            proof: 'application-proof'
        },
        showAccordionError: 0,
        showAccordionSuccess: 1
    })
    .constant("errorMessageConstants",
    {
        chooseOption: "Select an option.",
        invalidStreetAddress: "Enter a valid street address.",
        invalidCity: "Enter a valid city.",
        invalidState: "Enter a valid state.",
        invalidZip: "Enter a valid zip code. Five characters, numbers only.",
        invalidName: "Enter a valid first and last name.",
        invalidDob: "Select a valid date of birth.",
        invalidDocId: "Enter last 4 digits of document id.",
        invalidDobDoc: "Select a document.",
        invalidSSNDoc: "Select a document.",
        invalidSSN: "Enter the last 4 digits of your social security number.",
        invalidEmail: "Enter in a valid email address.",
        invalidfullSSN: "Enter your full social security number with no dashes.",
        invalidCurrentLifelinePhoneNumber: "Enter your valid current Lifeline phone number.",
        invalidLifelineProgram: "Select a lifeline program.",
        invalidHouseholdSize: "Enter a household size.",
        invalidHouseholdAverageIncome: "Enter your household's average income.",
        invalidHouseholdAverageIncomeDuration: "Select a duration (annually, monthly, bi-weekly).",
        invalidInitials: "Enter your initials to agree with your statements.",
        invalidHOHWorksheet: "Complete the IEH Worksheet.",
        invalidPhoneNumber: "Enter in a valid phone number.",
        invalidResidenceDuration: "Select a residence duration.",
        invalidPartnerReceives: "Select whether or not your spouce or domestic partner currently receives a lifeline discounted phone.",
        invalidOtherRoommate: "Describe the other roommate that lives with you.",
        invalidMultipleHouseholdAcceptance: "Certify that you live at an address occupied by multiple households.",
        invalidOnePerHouseholdAcceptance: "Certify that you understand a violation of the one-per-household requirement is against the Federal Communication Commission's rules.",
        invalidSignature: "Enter your signature.",
        invalidAgreementStatement: "Mark all of the agreement statements before continuing.",
        invalidDeviceChoice: "Select a device.",       
        invalidCompliance: "Please provide a response to the compliance statement.",
        applicantIsUnder18: "Applicant must be at least 18 years of age or older.",      
        invalidSort: "Sort must be numeric.",
        invalidPuertoRicoPenalty:"Certify that you understand the penalties for fraud or false certification to obtain Puerto Rico Lifeline services.",      
    });

